"""Frozen canonical hashes for a fixed corpus of specs.

`gate_canonical_reproducibility` (`saimc.release.gates`) compares two runs
of the *same build*, so a refactor that changes every byte still passes it —
both runs move together. Before this module nothing in the repo pinned an
engine output to a value recorded earlier, which is what makes
"byte-identical refactor" a checkable claim instead of an assertion.

The corpus is the axes the engine branches on hardest — mood, duration,
ensemble, and key — held against `tests/fixtures/golden_hashes.json`. The
key axis names a key in every cell, because `None` is not an axis the
corpus can hold: it is a *derived* value — the entry this seed walks to in
the mood's pool — so a cell for it would pin one seed's arithmetic, and
that is the weakest part of the derivation. `TestKeySelection` pins the
derivation directly instead, and this grid holds the key arithmetic fixed
across three named keys. Regenerate deliberately with
`SAIMC_UPDATE_GOLDEN_HASHES=1`, and put the pieces that changed in the
commit message: the regeneration diff is the review material.

`humanization` is deliberately not an axis — it is spec-level, the engine's
plan work does not reach it, and a wider grid is more churn to review on
every deliberate music change. Add it if a change reaches it.
"""

from __future__ import annotations

import json
import os
import zlib
from pathlib import Path
from typing import Any

import pytest

from saimc.canonical import CANONICAL_FORMAT_VERSION, canonical_sha256
from saimc.compose.engine import EngineOutput, compose
from saimc.compose.forms import MOOD_KEY_POOLS, key_signature_from_spec_key
from saimc.spec import (
    DURATION_SECONDS_DEFAULT,
    DURATION_SECONDS_MAX,
    DURATION_SECONDS_MIN,
    SPEC_SCHEMA_VERSION,
    CompositionSpec,
    Mood,
    WesternKey,
)

FIXTURE_PATH = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "golden_hashes.json"

UPDATE_ENV = "SAIMC_UPDATE_GOLDEN_HASHES"

MOODS = (Mood.CALMING, Mood.ELECTRIFYING, Mood.SLEEP)
DURATIONS = (DURATION_SECONDS_MIN, DURATION_SECONDS_DEFAULT, DURATION_SECONDS_MAX)
"""The floor, the default, and the §10 #11 cap."""

KEYS = ("C", "Am", "G")
"""Two modes and two roots — the axes a key actually varies on.

`None` (the engine's own choice) is deliberately not in the grid. It
resolves to the entry the seed walks to in the mood's pool, so it is a
function of a value this corpus already fixes per cell rather than an
independent axis; every one of the 25 keys `WesternKey` admits composes
clean, so there is no key for a cell to *reach* that a named cell does not
already cover. `TestKeySelection` pins the derivation itself, which is
where a reader can see what the engine picks rather than infer it from a
hash.
"""

_ENSEMBLES: dict[str, list[dict[str, str]] | None] = {
    "default": None,
    "trio": [
        {"role": "melody", "instrument": "piano"},
        {"role": "harmony", "instrument": "strings"},
        {"role": "bass", "instrument": "contrabass"},
    ],
    "full": [
        {"role": "melody", "instrument": "piano"},
        {"role": "harmony", "instrument": "strings"},
        {"role": "bass", "instrument": "contrabass"},
        {"role": "percussion", "instrument": "drum_set"},
    ],
}
"""`None` is the mood's own default ensemble; the other two add a rhythm
section, which is the axis the percussion path branches on."""

_FROZEN_SIDECAR_FIELDS = (
    "arrangement",
    "key",
    "time_signature",
    "chord_bars",
    "bar_keys",
    "voice_instruments",
)
"""The engine's musical decisions, as the linter and renderers read them.

A named subset rather than the whole sidecar on purpose: the composition
plan lands in the sidecar next, and a guard that has to be regenerated by
the change it guards is not a guard.
"""

FINGERPRINT_FIELDS = (
    "notation_score_sha256",
    "performance_plan_sha256",
    "engine_decisions_sha256",
    "note_count",
    "measure_count",
)


def _cell_id(mood: Mood, duration: int, ensemble: str) -> str:
    """The musical starting point: everything about an entry but its key."""
    return f"{mood.value}-{duration}-{ensemble}"


def _entry_id(mood: Mood, duration: int, ensemble: str, key: str) -> str:
    return f"{_cell_id(mood, duration, ensemble)}-{key}"


def _seed_for(cell_id: str) -> int:
    """A stable seed per *cell*, so the corpus does not depend on run order.

    Deliberately not per entry: the three key variants of a cell share a
    seed and are therefore comparable — varying only the key is a
    controlled comparison. Different cells are not comparable, which is
    what lets the corpus scatter across the seed space instead of pinning
    one; a controlled comparison across the other axes is a purpose-built
    probe, not something to read off this fixture.

    crc32 rather than the built-in `hash()`: `hash()` of a str is salted
    per process, so a fixture written under one interpreter would not
    reproduce under the next.
    """
    return 1 + zlib.crc32(cell_id.encode("utf-8")) % 99_999


def corpus() -> dict[str, CompositionSpec]:
    """The golden corpus: entry id -> spec, in a stable order."""
    specs: dict[str, CompositionSpec] = {}
    for mood in MOODS:
        for duration in DURATIONS:
            for ensemble, instrumentation in _ENSEMBLES.items():
                for key in KEYS:
                    entry_id = _entry_id(mood, duration, ensemble, key)
                    specs[entry_id] = CompositionSpec.model_validate(
                        {
                            "mood": mood.value,
                            "duration_seconds": duration,
                            "seed": _seed_for(_cell_id(mood, duration, ensemble)),
                            "key": key,
                            **(
                                {"instrumentation": instrumentation}
                                if instrumentation is not None
                                else {}
                            ),
                        }
                    )
    return specs


def _fingerprint(output: EngineOutput) -> dict[str, Any]:
    sidecar = output.to_sidecar()
    return {
        "notation_score_sha256": output.notation_score.compute_hash(),
        "performance_plan_sha256": output.performance_plan.compute_hash(),
        "engine_decisions_sha256": canonical_sha256(
            {field: sidecar[field] for field in _FROZEN_SIDECAR_FIELDS}
        ),
        "note_count": len(output.notation_score.notes),
        "measure_count": len(output.notation_score.measures),
    }


_fingerprints: dict[str, dict[str, Any]] | None = None


def _fingerprints_now() -> dict[str, dict[str, Any]]:
    """Compose and hash the whole corpus once per session."""
    global _fingerprints
    if _fingerprints is None:
        _fingerprints = {
            entry_id: _fingerprint(compose(spec)) for entry_id, spec in corpus().items()
        }
    return _fingerprints


def _load_fixture() -> dict[str, Any]:
    document: dict[str, Any] = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    return document


def _write_fixture() -> None:
    document = {
        "canonical_format_version": CANONICAL_FORMAT_VERSION,
        "spec_schema_version": SPEC_SCHEMA_VERSION,
        "entries": _fingerprints_now(),
    }
    FIXTURE_PATH.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")


@pytest.fixture(scope="module", autouse=True)
def _regenerate_when_asked() -> None:
    """Rewrite the fixture when `SAIMC_UPDATE_GOLDEN_HASHES` is set.

    The tests still run afterwards and read the file back, so a
    regeneration is verified against itself rather than trusted.
    """
    if os.environ.get(UPDATE_ENV):
        _write_fixture()


class TestGoldenHashCorpus:
    def test_the_declared_corpus_still_spans_every_axis(self) -> None:
        """A tripwire on the corpus shrinking.

        Dropping a mood or a duration would shrink the corpus and the
        fixture together, so the coverage check below would still pass.
        This is what makes that visible.
        """
        assert len(MOODS) * len(DURATIONS) * len(_ENSEMBLES) * len(KEYS) == 81
        assert len(corpus()) == 81

    def test_the_fixture_covers_exactly_the_declared_corpus(self) -> None:
        frozen = set(_load_fixture()["entries"])
        declared = set(corpus())
        report = []
        if missing := sorted(declared - frozen):
            report.append(f"{len(missing)} declared but absent from the fixture: {missing[:5]}")
        if orphaned := sorted(frozen - declared):
            report.append(f"{len(orphaned)} in the fixture but no longer declared: {orphaned[:5]}")
        assert not report, "\n".join(report)

    def test_every_entry_reproduces_its_frozen_hashes(self) -> None:
        """The engine still produces the canonical artifacts it did before.

        This is the assertion a byte-changing refactor fails and
        `gate_canonical_reproducibility` cannot: that gate runs the same
        build twice.
        """
        frozen = _load_fixture()["entries"]
        actual = _fingerprints_now()
        mismatches = []
        for entry_id in sorted(frozen):
            before, now = frozen[entry_id], actual[entry_id]
            changed = [field for field in FINGERPRINT_FIELDS if before[field] != now[field]]
            if changed:
                detail = ", ".join(f"{field} {before[field]} -> {now[field]}" for field in changed)
                mismatches.append(f"  {entry_id}: {detail}")
        assert not mismatches, (
            f"{len(mismatches)} of {len(frozen)} corpus entries no longer reproduce.\n"
            "If the change was meant to alter the music, regenerate with "
            f"{UPDATE_ENV}=1 and name the affected pieces in the commit message.\n"
            + "\n".join(mismatches[:20])
            + ("\n  (further mismatches omitted)" if len(mismatches) > 20 else "")
        )


class TestKeySelection:
    """What `key=None` does now: it walks the mood's pool.

    The engine is asked to choose a key whenever the parser leaves `key`
    unset — which is the default — and it picks `pool[seed % len(pool)]`
    from the mood's own pool, so consecutive seeds of a fan-out land on
    different keys rather than on one constant. Which keys, and in what
    order, is a taste call and is pinned as a literal in
    `tests/unit/test_compose_forms.py`; what this class pins is that the
    choice *is* being made, and that making it produces the same piece as
    writing the chosen key into the spec would.

    That second claim is the one that lets the corpus get away with a
    named key in every cell: if the unnamed path composes to exactly the
    named path for the key it picked, then the 81 named cells hold the key
    arithmetic and this class holds the lookup, and the two together leave
    no part of the derivation unmeasured.
    """

    def test_the_engine_walks_the_moods_own_pool(self) -> None:
        for mood in MOODS:
            pool = MOOD_KEY_POOLS[mood.value]
            assert len(pool) > 1, f"{mood} has one key, so nothing here is a choice"
            for seed in range(len(pool) * 2):
                key = compose(CompositionSpec(mood=mood, duration_seconds=60, seed=seed)).key
                expected = key_signature_from_spec_key(WesternKey(pool[seed % len(pool)]))
                assert (key.root, key.mode) == (expected.root, expected.mode), (mood, seed, key)

    def test_the_choice_is_reachable_at_every_seed_of_a_fan_out(self) -> None:
        """The property the harness needs, stated over the seeds it uses.

        A fan-out composes its candidates at `base + offset`, so it is the
        first few seeds in particular that have to differ from each other;
        a pool that only came apart at seed 30 would leave every fan-out
        showing the user four pieces in one key.
        """
        for mood in MOODS:
            chosen = {
                compose(CompositionSpec(mood=mood, duration_seconds=60, seed=seed)).key.root
                for seed in range(4)
            }
            assert len(chosen) == 4, (mood, chosen)

    def test_the_moods_do_not_fall_back_to_the_same_key(self) -> None:
        """A seedless spec takes each pool's head, and the heads differ.

        Three moods that landed on C would make the pool a formality for
        the commonest case, which is the one a caller who never thinks
        about keys gets.
        """
        heads = {
            compose(CompositionSpec(mood=mood, duration_seconds=60)).key.root for mood in MOODS
        }
        assert len(heads) == len(MOODS), heads

    def test_an_unnamed_key_is_byte_identical_to_naming_the_key_it_picked(self) -> None:
        """Not merely in the chosen key — the same piece.

        The stronger claim, and the one a reader would otherwise assume
        away when comparing two specs that differ only in this field. Run
        at every seed the pool's length reaches, so it covers every entry
        of every pool rather than whichever key one seed happens to land
        on.
        """
        for mood in MOODS:
            pool = MOOD_KEY_POOLS[mood.value]
            for seed in range(len(pool)):
                picked = pool[seed % len(pool)]
                auto = compose(CompositionSpec(mood=mood, duration_seconds=60, seed=seed))
                named = compose(
                    CompositionSpec(mood=mood, duration_seconds=60, seed=seed, key=picked)
                )
                assert auto.notation_score.compute_hash() == named.notation_score.compute_hash()
                assert auto.performance_plan.compute_hash() == named.performance_plan.compute_hash()
